name: Python Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Crear entorno virtual
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        source venv/bin/activate
        pytest test_app.py || true